server:
  servlet:
    context-path: /platform
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.13.45:3306/fundraising_platform?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: Ymk0910!
  servlet:
    multipart:
      max-file-size: 10MB


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml  #sql映射文件位置
#  configuration:
#    map-underscore-to-camel-case: true    #开启驼峰命命